### ISSUE TITLE
Meeting Notes 2023-11-02

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiraldiscovery#12]
- [x] Change ADaM IG guide column  to an additional resource column with links to IG as needed and links to the template examples @ddsjoberg 
- [x] Make the Reference nav link a list with interactive and list of functions (the current Reference link) [@ddsjoberg to create admiral issue]
- [x] Remove Data Set Type column from interactive tables [@ddsjoberg ]
- [x] Sort tables with ADSL first, then alphabetical [@ddsjoberg ]
- [ ] Something to think about: should we have any kind automated updates?
- [ ] Goal to release it with admiral v1.0
- [x] Review the admiral extension packages and add their variables as well. [@ddsjoberg to assign]

FYI @bms63 @bundfussr @zdz2101 @manciniedoardo

**Comment by bms63** [comment]
Thanks all!! Sorry I was absent today.

We are trying to do the release on December 4th just to keep eye on the timelines

I'm keen on automating if possible and where it makes sense.  Perhaps we can use Daphne's talents to aid in our mission?  I can't imagine we are going to have too many new functions in the future...so maybe it is a bit overkill.
