### ISSUE TITLE
Presentation Archive Glowup

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiraldiscovery#35]
We're currently using a markdown table to show the available presentations/resources.
![image](https://github.com/pharmaverse/admiraldiscovery/assets/26774684/f7a25c67-09f9-48e3-bd0e-6bd81ec61f3c)

We could give the table a glow-up by using gt. This will allow us to control the column widths (the title should be longer than the others), the links to the resources could use cute fontawesome icons, e.g. 
video 
![image](https://github.com/pharmaverse/admiraldiscovery/assets/26774684/4843d75c-0236-4919-aef2-5472c6c48414)
slides 
![image](https://github.com/pharmaverse/admiraldiscovery/assets/26774684/8d7ee08c-c1d3-4e35-979c-551a5f6481bd)
manuscript 
![image](https://github.com/pharmaverse/admiraldiscovery/assets/26774684/525a9bf3-8278-49b3-a97e-56bea21141b6)

@manciniedoardo this is your vignette, so i'll leave it up to you how you'd like to update or not!

**Comment by manciniedoardo** [comment]
On it! Thanks @ddsjoberg for the suggestion.
