### ISSUE TITLE
Add admiralpeds variables to listing

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiraldiscovery#51]
Now that admiralpeds is on CRAN, we can update our listing with these variables.

Do we have templates using creating these variables that we can link to (like we do for the other variables in the listing)? If not, would be great to add a template script to the package.

**Comment by Fanny-Gautier** [comment]
admiral-lookup-book.csv updated to add the {admiralpeds} variables, [PR](https://github.com/pharmaverse/admiraldiscovery/pull/53) created
