### ISSUE TITLE
Remove gt/reactable reference and just say Variable Listing Tab

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldiscovery#54]
We no longer surface the gt vignette - can we just say Variable Listing Tab

![image](https://github.com/user-attachments/assets/46ae8580-26f7-49c2-ab2d-3bf02266afa4)

**Comment by bms63** [comment]
@ddsjoberg - maybe a good one for R/Pharma!?!

**Comment by ddsjoberg** [comment]
Sounds great! Do you want to add this issue to the RIP DEI spreadsheet?
